@startuml "refar-institutions"

skinparam defaultFontName "Jetbrains Mono"
skinparam defaultFontSize 14
hide methods
hide circle
skinparam nodesep 100
skinparam ranksep 100

object "🗃️ Types d'institutions" as o_tdi {
    
}
o_tdi --> "crm:E32_Authority_Document" : "rdf:type"

object "🗃️ Types de charges" as o_tdf {
    
}
o_tdf --> "crm:E32_Authority_Document" : "rdf:type"

object "🏙️ Autun" as o_aut {
    
}
o_aut --> "crm:E53_Place" : "rdf:type"

object "🏷️ Archevêché" as o_arc  {
    
}
o_arc --> "crm:E55_Type" : "rdf:type"

object "🏷️ Évêché" as o_eve  {
    
}
o_eve --> "crm:E55_Type" : "rdf:type"

object "🏷️ Abbaye" as o_abb  {
    
}
o_abb --> "crm:E55_Type" : "rdf:type"

object "🏷️ Détention de fonction" as o_det  {
    
}
o_det --> "crm:E55_Type" : "rdf:type"

object "🧔‍♀️ Pierre" as o_e21 {
    
}
o_e21 --> "crm:E21_Person" : "rdf:type"

object "détention de fonction #01" as o_e7 #DeepPink {

}
o_e7 --> "crm:E7_Activity" : "rdf:type"

object "🏷️ Cuisinier" as o_cui {
    
}
o_cui --> "crm:E55_Type" : "rdf:type"

object "🗓️ 👤 ➡️ 👤👤👤👤" as o_e85 {
    
}
o_e85 --> "crm:E85_Joining" : "rdf:type"

object "⛪ Abbaye d'Autun" as o_e74 {

}
o_e74 --> "crm:E74_Group" : "rdf:type"

class crm:E7_Activity #MediumSlateBlue {}
class crm:E32_Authority_Document #MediumSlateBlue {}
class crm:E21_Person #MediumSlateBlue {}
class crm:E53_Place #MediumSlateBlue {}
class crm:E55_Type #MediumSlateBlue {}
class crm:E74_Group #MediumSlateBlue {}
class crm:E85_Joining #MediumSlateBlue {}

o_tdi --> o_arc : "crm:P71_lists"
o_tdi --> o_eve : "crm:P71_lists"
o_tdi --> o_abb : "crm:P71_lists"
o_tdf --> o_cui : "crm:P71_lists"

o_eve --> o_arc : "crm:P150_defines_typical_parts_of"
o_abb --> o_eve : "crm:P150_defines_typical_parts_of"
o_abb --> o_arc : "crm:P150_defines_typical_parts_of"

o_e7 --> o_det : "crm:P2_has_type"
o_e7 --> o_e21 : "crm:P14_carried_out_by"
o_e7 --> o_e74 : "crm:P12_occurred_in_the_presence_of"
o_e7 --> o_cui : "crm:P21_had general_purpose"
o_e85 --> o_e7 : "crmsci:O13_triggers"
o_e85 --> o_e21 : "crm:P143_joined"
o_e85 --> o_e74 : "crm:P144_joined_with"
o_e74 --> o_abb : "crm:P2_has_type"

@enduml