@startuml "refar-institutions"

skinparam defaultFontName "Recursive"
skinparam defaultFontSize 14
hide methods
hide circle

object archevêché #Aquamarine {
    skos:prefLabel: « Archevêché »
}

object types_d_institutions #Aquamarine {
    dcterms:title « Types d'institutions »
}

class skos:Concept #DeepPink {

}

class skos:ConceptScheme #DeepPink {

}

archevêché --> "skos:Concept" : "rdf:type"
archevêché --> types_d_institutions : "skos:inScheme"
types_d_institutions --> "skos:ConceptScheme" : "rdf:type"

@enduml